import assert from "node:assert/strict";
import { createVerticalCase, addEvidenceItem } from "../../safedesk-evidence/src/index.js";
import { renderCaseReportMarkdown, renderCaseReportHtml } from "../src/index.js";
const c = createVerticalCase("creator", { title: "Photo delivery proof", summary: "Client approved final edit." });
addEvidenceItem(c, { type: "approval", title: "Client email approval" });
const md = renderCaseReportMarkdown(c);
assert.match(md, /Creator proof pack/);
assert.match(md, /Important limitation/);
assert.match(renderCaseReportHtml(c), /<!doctype html>/);
console.log("safedesk-reports tests passed");
