import assert from "node:assert/strict";
import { AgentFirewall } from "../src/agentic/index.js";
const broadApprovalSpecificAllow = new AgentFirewall({ policy: { defaultAction: "deny", allowedActions: ["filesystem.read"], approvalRequired: ["filesystem.*"], blockedActions: [] } });
assert.equal(broadApprovalSpecificAllow.evaluateAction({ toolName: "filesystem", operation: "read" }).decision, "allow");
assert.equal(broadApprovalSpecificAllow.evaluateAction({ toolName: "filesystem", operation: "write" }).decision, "needs_approval");
const broadAllowSpecificApproval = new AgentFirewall({ policy: { defaultAction: "deny", allowedActions: ["*"], approvalRequired: ["database.*"], blockedActions: [] } });
assert.equal(broadAllowSpecificApproval.evaluateAction({ toolName: "search", operation: "read" }).decision, "allow");
assert.equal(broadAllowSpecificApproval.evaluateAction({ toolName: "database", operation: "query" }).decision, "needs_approval");
const explicitDenyWins = new AgentFirewall({ policy: { defaultAction: "allow", allowedActions: ["filesystem.delete"], approvalRequired: ["filesystem.delete"], blockedActions: ["filesystem.delete"] } });
assert.equal(explicitDenyWins.evaluateAction({ toolName: "filesystem", operation: "delete" }).decision, "deny");
const sameSpecificity = new AgentFirewall({ policy: { defaultAction: "deny", allowedActions: ["mcp.*"], approvalRequired: ["mcp.*"], blockedActions: [] } });
assert.equal(sameSpecificity.evaluateAction({ toolName: "mcp", operation: "tool_call" }).decision, "needs_approval");
console.log("agentic-policy-specificity.test.js passed");
