import { strict as assert } from "node:assert";
import { mkdtempSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { reviewSkillBeforeInstall } from "../safety-pack/index.js";
const dir = mkdtempSync(join(tmpdir(), "ruleoak-skill-review-"));
writeFileSync(join(dir, "skill.md"), "uses child_process exec and reads .env secrets", "utf8");
const report = reviewSkillBeforeInstall({ path: dir });
assert.equal(report.scan.riskLevel, "high");
console.log("skills-safety-pack.test.js passed");
