import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { summarizeReport } from './report-catalog.js';

function esc(value) {
  return String(value ?? '').replace(/[&<>\"]/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[ch]));
}

function rows(items = []) {
  if (!Array.isArray(items) || items.length === 0) return '<p>No records.</p>';
  return `<table><thead><tr><th>ID</th><th>Type</th><th>Summary</th></tr></thead><tbody>${items.map((item) => `<tr><td>${esc(item.id || item.recordId || item.tool || '')}</td><td>${esc(item.type || item.recordType || item.decision || item.status || '')}</td><td>${esc(item.summary || item.title || item.reason || item.action || item.claim || JSON.stringify(item).slice(0, 160))}</td></tr>`).join('')}</tbody></table>`;
}

export function renderReport(report, options = {}) {
  const summary = summarizeReport(report, options.sourcePath || 'report.json');
  const title = summary.title || 'RuleOak report';
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>body{font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:#08111f;color:#eef5ff;margin:0;padding:40px;line-height:1.5}.shell{max-width:1080px;margin:0 auto}.card{background:#0d1b2e;border:1px solid #28405f;border-radius:18px;padding:24px;margin:18px 0}h1,h2{color:#fff}code{background:#14243a;padding:2px 6px;border-radius:6px}table{border-collapse:collapse;width:100%;margin-top:12px}th,td{border-bottom:1px solid #28405f;text-align:left;padding:10px;vertical-align:top}.badge{display:inline-block;border:1px solid #d6b56d;color:#ffe3a3;border-radius:999px;padding:4px 10px;margin-right:8px}.muted{color:#aec0d6}</style></head><body><main class="shell"><h1>${esc(title)}</h1><p class="muted">Generated by RuleOak local report renderer. Source: <code>${esc(options.sourcePath || '')}</code></p><section class="card"><h2>Summary</h2><p><span class="badge">${esc(summary.status)}</span><span class="badge">${esc(summary.policyDecision)}</span><span class="badge">${esc(summary.runtimeStage)}</span></p><pre>${esc(JSON.stringify(report.summary || report.run || {}, null, 2))}</pre></section><section class="card"><h2>Evidence</h2>${rows(report.evidence)}</section><section class="card"><h2>Policy decisions</h2>${rows(report.toolDecisions || report.policyDecisions)}</section><section class="card"><h2>Approvals</h2>${rows(report.approvals)}</section><section class="card"><h2>Audit events</h2>${rows(report.auditEvents)}</section></main></body></html>`;
}

export function renderReportFile(inputPath, outputPath) {
  const report = JSON.parse(readFileSync(inputPath, 'utf8'));
  const html = renderReport(report, { sourcePath: inputPath });
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, html);
  return outputPath;
}
