import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, basename, join, resolve } from "node:path";

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function titleOf(report) {
  return report.app || report.run?.app || report.output?.demo || report.demo || report.summary?.title || report.summary?.question || "RuleOak Report";
}

function asList(items) {
  if (!Array.isArray(items) || items.length === 0) return '<p class="muted">None recorded.</p>';
  return `<ul>${items.map((item) => `<li>${escapeHtml(typeof item === "string" ? item : (item.claim || item.summary || JSON.stringify(item)))}</li>`).join("")}</ul>`;
}

function evidenceHtml(report) {
  const evidence = report.evidence || report.evidenceRecords || report.output?.claims || [];
  if (!Array.isArray(evidence) || evidence.length === 0) return '<p class="muted">No evidence records.</p>';
  return evidence.map((e) => {
    const id = e.id || e.source || e.claim || "evidence";
    const claim = e.claim || e.summary || e.title || JSON.stringify(e);
    const value = e.value || (Array.isArray(e.evidence) ? e.evidence.join(" | ") : "");
    const sources = e.sourceIds || e.source_ids || [];
    return `<article class="record"><strong>${escapeHtml(id)}</strong><p>${escapeHtml(claim)}</p>${value ? `<code>${escapeHtml(value)}</code>` : ""}${sources.length ? `<p class="muted">Sources: ${escapeHtml(sources.join(", "))}</p>` : ""}</article>`;
  }).join("\n");
}

function auditHtml(report) {
  const events = report.audit?.events || report.auditEvents || [];
  if (!Array.isArray(events) || events.length === 0) return '<p class="muted">No audit events recorded in this report.</p>';
  return events.slice(0, 12).map((e) => `<article class="record"><strong>${escapeHtml(e.type || e.event || e.status || "event")}</strong><p>${escapeHtml(e.message || e.action || e.decision || JSON.stringify(e))}</p></article>`).join("\n");
}

function decisionHtml(report) {
  const decisions = [];
  if (report.summary?.policyDecision) decisions.push(["Policy decision", report.summary.policyDecision]);
  if (report.summary?.approvalStatus) decisions.push(["Approval", report.summary.approvalStatus]);
  if (report.summary?.exportDecision) decisions.push(["Export", report.summary.exportDecision]);
  if (report.summary?.publishDecision) decisions.push(["Publish", report.summary.publishDecision]);
  if (report.output?.policyDecision) decisions.push(["Action", `${report.output.policyDecision.decision} (${report.output.policyDecision.reason || "no reason"})`]);
  if (report.output?.policy_decisions?.publish) decisions.push(["Publish", report.output.policy_decisions.publish.decision]);
  if (decisions.length === 0) return '<p class="muted">No policy decisions found.</p>';
  return `<dl>${decisions.map(([k, v]) => `<dt>${escapeHtml(k)}</dt><dd>${escapeHtml(v)}</dd>`).join("")}</dl>`;
}

export function renderReportHtml(report, sourcePath = "") {
  const title = titleOf(report);
  const summaryTitle = report.summary?.title || report.summary?.question || report.output?.question?.question || report.output?.case?.title || title;
  const cause = report.summary?.probableCause || report.summary?.recommendation || report.output?.probableCause || report.output?.recommendation?.summary || "See details below.";
  const recommendations = report.output?.recommendation || report.recommendation || report.output?.recommendation?.rationale || [];
  const boundary = report.boundary || report.ruleoak_boundary?.note || report.boundaryNote || "Generated by RuleOak. Review before acting.";
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: dark; --bg:#08111f; --panel:#0d1b2e; --panel2:#13243b; --text:#eef5ff; --muted:#9fb3ca; --accent:#d6b56d; --ok:#9fd3b8; --line:#2a405e; }
    body { margin:0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif; background: radial-gradient(circle at top left, #172a46, var(--bg)); color:var(--text); }
    main { max-width:1080px; margin:0 auto; padding:40px 22px 80px; }
    .hero { border:1px solid var(--line); background:rgba(13,27,46,.82); border-radius:26px; padding:28px; box-shadow:0 20px 80px rgba(0,0,0,.24); }
    .eyebrow { color:var(--accent); text-transform:uppercase; letter-spacing:.12em; font-size:12px; font-weight:700; }
    h1 { font-size:clamp(30px,5vw,54px); line-height:1; margin:10px 0; }
    h2 { margin:0 0 12px; font-size:24px; }
    p { color:var(--muted); line-height:1.65; }
    .grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:18px; margin-top:18px; }
    .card,.record { background:rgba(19,36,59,.88); border:1px solid var(--line); border-radius:18px; padding:18px; }
    .section { margin-top:24px; }
    code, pre { background:#07101d; border:1px solid #243853; color:#dbeafe; border-radius:12px; padding:10px; display:block; white-space:pre-wrap; overflow:auto; }
    dl { display:grid; grid-template-columns:180px 1fr; gap:10px; }
    dt { color:var(--accent); font-weight:700; } dd { margin:0; color:var(--text); }
    ul { margin:0; padding-left:22px; } li { margin:8px 0; color:var(--muted); }
    .muted { color:var(--muted); }
    .badge { display:inline-block; padding:7px 10px; border-radius:999px; background:rgba(159,211,184,.12); color:var(--ok); border:1px solid rgba(159,211,184,.35); margin-right:8px; }
    @media (max-width:760px){.grid{grid-template-columns:1fr;} dl{grid-template-columns:1fr;}}
  </style>
</head>
<body>
<main>
  <section class="hero">
    <div class="eyebrow">RuleOak one-page report</div>
    <h1>${escapeHtml(summaryTitle)}</h1>
    <p>${escapeHtml(cause)}</p>
    <span class="badge">${escapeHtml(report.runtimeStage || "early-runtime")}</span>
    <span class="badge">${escapeHtml(report.run?.status || "generated")}</span>
    <p class="muted">Source: ${escapeHtml(sourcePath ? basename(sourcePath) : "generated report")}</p>
  </section>

  <section class="section grid">
    <div class="card"><h2>Policy decisions</h2>${decisionHtml(report)}</div>
    <div class="card"><h2>Boundary</h2><p>${escapeHtml(boundary)}</p><p class="muted">This report is audit-style output, not compliance certification or production authority.</p></div>
  </section>

  <section class="section card"><h2>Recommendations</h2>${asList(Array.isArray(recommendations) ? recommendations : [recommendations])}</section>
  <section class="section card"><h2>Evidence / Claims</h2>${evidenceHtml(report)}</section>
  <section class="section card"><h2>Audit trail</h2>${auditHtml(report)}</section>

  <section class="section card"><h2>Raw JSON</h2><pre>${escapeHtml(JSON.stringify(report, null, 2))}</pre></section>
</main>
</body>
</html>`;
}

export function renderReportFile(inputPath, outputPath) {
  const fullInput = resolve(inputPath);
  if (!existsSync(fullInput)) throw new Error(`Report not found: ${inputPath}`);
  const report = JSON.parse(readFileSync(fullInput, "utf8"));
  const out = outputPath || join(dirname(fullInput), basename(fullInput).replace(/\.json$/i, ".html"));
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, renderReportHtml(report, fullInput));
  return out;
}
